name: build

on: [ push, pull_request ]

jobs:
  make:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: make
        run: |
          git submodule init
          git submodule update
          sudo apt-get update
          sudo apt install make gcc build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
          make -j$(nproc)
  make_warns_free:
    runs-on: ubuntu-latest
    needs: make
    steps:
      - uses: actions/checkout@v2
      - name: make warns free
        run: |
          git submodule init
          git submodule update
          sudo apt-get update
          sudo apt install make gcc build-essential libasound2-dev mesa-common-dev libx11-dev libxrandr-dev libxi-dev xorg-dev libgl1-mesa-dev libglu1-mesa-dev
          make WARNS=-Werror -j$(nproc) -B
