name: shader-check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fragment-shader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cat shaders/*.frag.glsl > full.frag
        ./glslangValidator full.frag
        
  vertex-shader:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cat shaders/*.vert.glsl > full.vert
        ./glslangValidator full.vert
